# Generated by Django 4.2.11 on 2024-05-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewModel',
        ),
    ]
