# Generated by Django 4.2.11 on 2024-05-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlibraryaccount',
            name='image',
        ),
    ]
