# Generated by Django 4.2.11 on 2024-05-27 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookmodel_image'),
        ('borrow', '0004_reviewmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.bookmodel'),
        ),
    ]
